version: '2'

services:
  redis:
    container_name: redis_raffle
    image: redis:alpine
    ports:
      - '6379:6379'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
