export enum ROLE_ENUM {
  USER = 'USER',
  ADMIN = 'ADMIN',
  DEV = 'DEV',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}

export enum PUBLIC_ROLE_ENUM {
  USER = 'USER',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}
