export enum ASAAS_BILING_TYPE_ENUM {
  BOLETO = 'BOLETO',
  CREDIT_CARD = 'CREDIT_CARD',
  UNDEFINED = 'UNDEFINED',
  DEBIT_CARD = 'DEBIT_CARD',
  TRANSFER = 'TRANSFER',
  DEPOSIT = 'DEPOSIT',
  PIX = 'PIX',
}
